# Generated by Django 4.0.3 on 2023-01-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('attachment_list', models.CharField(max_length=70)),
                ('published_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'article_tbl',
            },
        ),
    ]
