# Generated by Django 4.0.3 on 2023-01-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_excludexpath_xpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpath',
            name='link_liet',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='excludexpath',
            name='exclude_element_xpath',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='excludexpath',
            name='site_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
