# Generated by Django 4.0.3 on 2023-01-23 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_xpath_published_datetime_xpath_published_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xpath',
            old_name='link_liet',
            new_name='link_list',
        ),
    ]
