# Generated by Django 4.0.3 on 2023-01-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_link_liet_xpath_link_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_datetime',
            field=models.DateTimeField(),
        ),
    ]
