# Generated by Django 4.0.3 on 2023-01-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_published_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='', max_length=20)),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'failure_link_tbl',
            },
        ),
    ]
