# Generated by Django 4.0.3 on 2023-01-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_failurelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='attachment_list',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='site_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
